---
title: "Scientific Data Figures"
author: "Andrew Chen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: 'united'
    toc: true
    toc_depth: 1
    toc_float: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
library(Seurat)
library(tidyverse)
library(cowplot)
library(scCustomize)

PATH <- file.path(Sys.getenv("MLAB"), "projects/brcameta/brca_atlas")

source(file.path(PATH, "scripts/util.R"))
```

# S1
```{r}
combined_seurat_filtered <- readRDS(file.path(PATH, "data/sc/combined_seurat_filtered_int.rds"))
```

```{r}
combined_seurat_filtered$celltypist_short <- celltypist_short(combined_seurat_filtered$celltypist_pred)
combined_seurat_filtered$singler_short <- singler_short(combined_seurat_filtered$singler_pred)
combined_seurat_filtered$author_short <- author_short(combined_seurat_filtered$celltype_new)
p1 <- scCustomize::DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.pca",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title="Dataset", x = "UMAP1", y="UMAP2")
p2 <- scCustomize::DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.pca",
  group.by = "subtype_new",
  label = FALSE,
  raster = FALSE
) + labs(title="Subtype", x = "UMAP1", y="UMAP2")
p3 <- scCustomize::DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.pca",
  group.by = "celltypist_short",
  label = TRUE,
  label.size = 3,
  repel = TRUE,
  raster = FALSE
) + labs(title="CellTypist", x = "UMAP1", y="UMAP2")
p4 <- scCustomize::DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.pca",
  group.by = "singler_short",
  label = TRUE,
  label.size = 3,
  repel = TRUE,
  raster = FALSE
) + labs(title="SingleR", x = "UMAP1", y="UMAP2")
p5 <- scCustomize::DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.pca",
  group.by = "author_short",
  label = TRUE,
  label.size = 3, 
  repel = TRUE,
  raster = FALSE
) + labs(title="Author", x = "UMAP1", y="UMAP2")
p6 <- scCustomize::DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.pca",
  group.by = "grade",
  label = FALSE,
  raster = FALSE
) + labs(title="Grade", x = "UMAP1", y="UMAP2")
first_row <- cowplot::plot_grid(p1, p2, p6, ncol = 3)
second_row <- cowplot::plot_grid(p3, p4, p5, ncol = 3)
combined_plot <- cowplot::plot_grid(first_row, second_row, ncol = 1, rel_heights = c(1, 1))

ggsave(plot = combined_plot, file.path(PATH, "results/umaps/umap_all_unintegrated.png"), width = 20, height = 10)
```

# S2
```{r}
p1 <- DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.harmony",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title = "Harmony", x = "UMAP 1", y = "UMAP 2") 
p2 <- DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.rpca",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title = "RPCA", x = "UMAP 1", y = "UMAP 2") 
p3 <- DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.mnn",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title = "MNN", x = "UMAP 1", y = "UMAP 2") 
p4 <- DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.scvi",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title = "scvi", x = "UMAP 1", y = "UMAP 2") 
p5 <- DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.scanvi_ct",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title = "scanvi (ct)", x = "UMAP 1", y = "UMAP 2") 
p6 <- DimPlot_scCustom(
  combined_seurat_filtered,
  reduction = "umap.scanvi_sub_ct",
  group.by = "batch",
  label = FALSE,
  raster=FALSE
) + labs(title = "scanvi (sub, ct)", x = "UMAP 1", y = "UMAP 2") 

p1 + p2 + p3 + p4 + p5 + p6 + patchwork::plot_layout(guides = 'collect')

ggsave(filename = file.path(PATH, "results/umaps/all_integration_batch.png"), width = 20, height = 10)
```

# S3
```{r}
combined_seurat_rpca <- DietSeurat(combined_seurat_filtered,
                                   layers = c("counts", "data", "scale.data"),
                                   assays = c("RNA"),
                                   dimreducs = c("pca", "umap.pca",
                                                 "integrated.rpca", "umap.rpca"))
combined_seurat_rpca <- FindNeighbors(combined_seurat_rpca, dims = 1:200, reduction = "integrated.rpca")
combined_seurat_rpca <- FindClusters(combined_seurat_rpca, resolution = 0.1)
```

```{r}
# Comparing broad annotations
p1 <- DimPlot_scCustom(combined_seurat_rpca,
                       reduction = "umap.rpca",
                       group.by = "RNA_snn_res.0.1",
                       raster = FALSE) + labs(title = "Clustering (0.2)", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position="none")
p2 <- DimPlot_scCustom(combined_seurat_rpca,
                       reduction = "umap.rpca",
                       group.by = "singleR_broad",
                       raster = FALSE) + labs(title = "SingleR", x = "UMAP 1", y = "UMAP 2")
p3 <- DimPlot_scCustom(combined_seurat_rpca,
                       reduction = "umap.rpca",
                       group.by = "celltypist_broad",
                       raster = FALSE) + labs(title = "Celltypist", x = "UMAP 1", y = "UMAP 2")
p4 <- DimPlot_scCustom(combined_seurat_rpca,
                       reduction = "umap.rpca",
                       group.by = "author_broad",
                       raster = FALSE) + labs(title = "Author", x = "UMAP 1", y = "UMAP 2")
combined <- cowplot::plot_grid(p1, p2, p3, p4, ncol=2, nrow = 2)

ggsave(plot = combined, filename = file.path(PATH, "results/umaps/all_clustering_broad_01.png"),
       width = 9, height = 8)
```

# S4
```{r}
epi_subset <- readRDS(file.path(PATH, "data/sc/epi_rpca_subset.rds"))
```

```{r}
epi_subset <- subset(epi_subset,
                     subset = RNA_snn_res.0.1 %in% c(18,2,1,13,0,3,5,14,17,22,4,6,15,16,8,20)) # remove low entropy clusters here
epi_subset$RNA_snn_res.0.1 <- droplevels(epi_subset$RNA_snn_res.0.1)
Idents(epi_subset) <- epi_subset$RNA_snn_res.0.1 
```

```{r}
epi_mast_tables <- readRDS(file.path(PATH, "results/clustering/epi_01_mast_markers.rds"))
epi_top5 <- epi_mast_tables %>% 
  dplyr::filter(cluster %in% unique(Idents(epi_subset))) %>%
  dplyr::mutate(cluster = factor(cluster, levels = levels(Idents(epi_subset))),
                pct.diff = pct.1 - pct.2) %>% 
  dplyr::filter(pct.diff > 0.1) %>%
  dplyr::group_by(cluster) %>%
  dplyr::arrange(p_val_adj, desc(avg_log2FC)) %>% 
  dplyr::slice_head(n = 5) %>%
  ungroup()
extra_cluster_0 <- epi_mast_tables %>% 
  dplyr::filter(cluster == 0) %>% 
  dplyr::mutate(pct.diff = pct.1 - pct.2) %>% 
  dplyr::arrange(p_val_adj, desc(avg_log2FC)) %>% slice(1:4)
epi_top5 <- rbind(extra_cluster_0, epi_top5)
```

```{r}
epi_heatmap <- DoHeatmap(epi_subset, features = epi_top5$gene, angle = 90, size = 3.5, hjust=1, lines.width = 600, group.bar = TRUE) + 
  theme(axis.text.y = element_text(size = 12))
ggsave(plot = epi_heatmap, 
       filename = file.path(PATH, "results/final_figures/epi_mast_heatmap.png"),
       width = 13, height = 14)
```

# S5
```{r}
imm_rpca <- readRDS(file.path(PATH, "data/sc/imm_rpca_subset.rds"))
imm_rpca$RNA_snn_res.0.6 <- factor(imm_rpca$RNA_snn_res.0.6, levels = 0:28)
Idents(imm_rpca) <- imm_rpca$RNA_snn_res.0.6
```

```{r}
lymphoid_mast_tables <- readRDS(file.path(PATH, "results/clustering/lymphoid_06_mast_markers.rds"))
myeloid_mast_tables <- readRDS(file.path(PATH, "results/clustering/myeloid_06_mast_markers.rds"))
imm_mast_tables <- rbind(lymphoid_mast_tables, myeloid_mast_tables)

imm_top5 <- imm_mast_tables %>%
  dplyr::filter(cluster %in% unique(Idents(imm_rpca))) %>%
  dplyr::mutate(cluster = factor(cluster, levels = levels(Idents(imm_rpca))),
                pct.diff = pct.1 - pct.2) %>%
  dplyr::filter(pct.diff > 0.1) %>%
  dplyr::group_by(cluster) %>%
  dplyr::arrange(p_val_adj, desc(avg_log2FC)) %>%
  dplyr::slice_head(n = 5) %>%
  ungroup()
```

```{r}
imm_heatmap <- DoHeatmap(imm_rpca, features = imm_top5$gene, angle = 90, size = 3.5, hjust=1, lines.width = 800, group.bar = TRUE) + theme(axis.text.y = element_text(size = 12))
ggsave(plot = imm_heatmap, 
       filename = file.path(PATH, "results/final_figures/imm_mast_heatmap.png"),
       width = 18, height = 15)
```

# S6
```{r}
imm_rpca$celltypist_imm_only <- with(imm_rpca@meta.data, 
                                     case_when(celltypist_broad == "Immune" ~ celltypist_pred,
                                               .default = celltypist_broad))
imm_rpca$singler_pred <- str_replace(imm_rpca$singler_pred, ", alpha-beta T cell", "")
imm_rpca$singler_pred <- str_replace(imm_rpca$singler_pred, ", alpha-beta memory T cell", " memory")
imm_rpca$singler_pred <- str_replace(imm_rpca$singler_pred, " positive memory", "positive memory")
imm_rpca$singler_pred <- str_replace(imm_rpca$singler_pred, "conventional dendritic cell", "cDC")
imm_rpca$singler_pred <- str_replace(imm_rpca$singler_pred, "plasmacytoid dendritic cell", "cDC")
imm_rpca$singler_pred <- str_replace(imm_rpca$singler_pred, "cell", "")
imm_rpca$singler_imm_only <- with(imm_rpca@meta.data, 
                                  case_when(singleR_broad == "Immune" ~ singler_pred,
                                            .default = singleR_broad))
imm_rpca$author_imm_only <- with(imm_rpca@meta.data, 
                                 case_when(author_broad == "Immune" ~ celltype_new,
                                           .default = author_broad))
Idents(imm_rpca) <- imm_rpca$RNA_snn_res.0.6

p1 <- DimPlot_scCustom(imm_rpca,
                       reduction = "umap.rpca",
                       group.by = "RNA_snn_res.0.6",
                       label = TRUE,
                       label.size = 3,
                       raster = FALSE,
                       repel = TRUE) + labs(title = "Clustering (0.6)", x = "UMAP 1", y = "UMAP 2")
p2 <- DimPlot_scCustom(seurat_object = imm_rpca,
                       group.by = "celltypist_imm_only",
                       reduction = "umap.rpca",
                       label = TRUE,
                       label.size = 2,
                       label.box = TRUE,
                       repel = TRUE,
                       raster = FALSE) + 
  labs(title = "Celltypist", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position = "none")
p3 <- DimPlot_scCustom(seurat_object = imm_rpca,
                       group.by = "singler_imm_only",
                       reduction = "umap.rpca",
                       label = TRUE,
                       label.size = 2, 
                       label.box = TRUE,
                       repel = TRUE,
                       raster = FALSE) + 
  labs(title = "SingleR", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position = "none")
p4 <- DimPlot_scCustom(imm_rpca,
                       reduction = "umap.rpca",
                       group.by = "author_imm_only",
                       label = TRUE,
                       label.size = 2,
                       label.box = TRUE,
                       repel = TRUE, 
                       raster = FALSE) + 
  labs(title = "Author", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position = "none")
combined <- cowplot::plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2)
ggsave(plot = combined, filename = file.path(PATH, "results/umaps/imm_rpca_annot_06.png"), height = 8, width = 11)
combined
```

# S7
```{r}
strom_rpca <- readRDS(file.path(PATH, "data/sc/strom_rpca_subset.rds"))
```

```{r}
strom_mast_tables <- readRDS(file.path(PATH, "results/clustering/strom_04_mast_markers.rds"))
strom_rpca$RNA_snn_res.0.4 <- factor(strom_rpca$RNA_snn_res.0.4, levels = 0:16)
Idents(strom_rpca) <- strom_rpca$RNA_snn_res.0.4
# Filtering expression in cluster 
strom_top5 <- strom_mast_tables %>% 
  dplyr::filter(cluster %in% unique(Idents(strom_rpca))) %>% 
  dplyr::mutate(pct.diff = pct.1 - pct.2) %>% 
  dplyr::filter(pct.diff > 0.1) %>%
  dplyr::group_by(cluster) %>%
  dplyr::arrange(p_val_adj, desc(avg_log2FC)) %>% 
  dplyr::slice_head(n = 5) %>%
  ungroup()
```


```{r}
strom_heatmap <- DoHeatmap(strom_rpca, features = strom_top5$gene, angle = 90, size = 3.5, hjust=1, lines.width = 600, group.bar = TRUE) + theme(axis.text.y = element_text(size = 12))
ggsave(plot = strom_heatmap, 
       filename = file.path(PATH, "results/final_figures/strom_mast_heatmap.png"),
       width = 13, height = 14)
```

# S8
```{r}
strom_rpca$celltypist_strom_only <- with(strom_rpca@meta.data, 
                                     case_when(celltypist_broad == "Stromal" ~ celltypist_pred,
                                               celltypist_broad != "Stromal" ~ NA,
                                               .default = celltypist_broad))
strom_rpca$singler_strom_only <- with(strom_rpca@meta.data, 
                                     case_when(singleR_broad == "Stromal" ~ singler_pred,
                                               singleR_broad != "Stromal" ~ NA,
                                               .default = singleR_broad))
strom_rpca$author_strom_only <- with(strom_rpca@meta.data, 
                                     case_when(author_broad == "Stromal" ~ celltype_new,
                                               # author_broad != "Stromal" ~ NA,
                                               .default = author_broad))
Idents(strom_rpca) <- strom_rpca$RNA_snn_res.0.4
p1 <- DimPlot_scCustom(strom_rpca,
                       reduction = "umap.rpca",
                       group.by = "RNA_snn_res.0.4",
                       label = TRUE,
                       label.size = 3,
                       repel = TRUE, 
                       raster = FALSE) + labs(title = "Clustering (0.4)", x = "UMAP 1", y = "UMAP 2")
p2 <- DimPlot_scCustom(strom_rpca,
                       reduction = "umap.rpca",
                       group.by = "celltypist_strom_only",
                       label = TRUE,
                       label.size = 2,
                       label.box = TRUE,
                       repel = TRUE, 
                       raster = FALSE) + 
  labs(title = "Celltypist", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position = "none")
p3 <- DimPlot_scCustom(strom_rpca,
                       reduction = "umap.rpca",
                       group.by = "singler_strom_only",
                       label = TRUE,
                       label.size = 2,
                       label.box = TRUE,
                       repel = TRUE, 
                       raster = FALSE) + 
  labs(title = "SingleR", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position = "none")
p4 <- DimPlot_scCustom(strom_rpca,
                       reduction = "umap.rpca",
                       group.by = "author_strom_only",
                       label = TRUE,
                       label.size = 2,
                       label.box = TRUE,
                       repel = TRUE, 
                       raster = FALSE) + 
  labs(title = "Author", x = "UMAP 1", y = "UMAP 2") +
  theme(legend.position = "none")
combined <- cowplot::plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2)
ggsave(plot = combined, filename = file.path(PATH, "results/umaps/stromal_rpca_annot_04.png"), height = 8, width = 11)
```

# S9
See `06b_infercnv_seurat.R`

